server:
  port: 8080

core-information-service:
  url: "http://localhost:8088"
  path: "/bookById/%s"
  connect-timeout: 100
  read-timeout: 200

description-store:
  url: "http://localhost:8088"
  path: "/descriptionById/%s"
  connect-timeout: 100
  read-timeout: 200
  retry-read-timeout: 1000
  cache:
    size: 500
    refresh_after_write: 600
    expire_after_write: 3600

stock-service:
    url: "http://localhost:8088"
    path: "/stockById/%s"
    connect-timeout: 100
    read-timeout: 200