server:
  port: 8080

spring:
  jmx:
    enabled: true

core-information-service:
  url: "http://localhost:8088"
  path: "/bookById/%s"
  connect-timeout: 100
  read-timeout: 1000
  retry-read-timeout: 2000

description-store:
  url: "http://localhost:8088"
  path: "/descriptionById/%s"
  connect-timeout: 100
  read-timeout: 1000
  cache:
    size: 500
    refresh_after_write: 1
    expire_after_write: 1

stock-service:
    url: "http://localhost:8088"
    path: "/stockById/%s"
    connect-timeout: 100
    read-timeout: 10000
    circuit-breaker:
      enabled: true
      failure-rate-threshold: 99
      wait-duration-in-open-state-in-millis: 30000
      permitted-number-of-calls-in-half-open-state: 10
      sliding-window-size: 25
      minimum-number-of-calls: 25