server:
  port: 8080

spring:
  jmx:
    enabled: true

core-information-service:
  url: "http://localhost:8088"
  path: "/bookById/%s"
  connect-timeout: 100
  read-timeout: 1000

description-store:
  url: "http://localhost:8088"
  path: "/descriptionById/%s"
  connect-timeout: 100
  read-timeout: 1000

stock-service:
    url: "http://localhost:8088"
    path: "/stockById/%s"
    connect-timeout: 100
    read-timeout: 1000