server:
  port: 8080

spring:
  jmx:
    enabled: true

core-information-service:
  url: "http://localhost:8088"
  path: "/bookById/%s"
  connect-timeout:
  read-timeout:

description-store:
  url: "http://localhost:8088"
  path: "/descriptionById/%s"
  connect-timeout:
  read-timeout:

stock-service:
    url: "http://localhost:8088"
    path: "/stockById/%s"
    connect-timeout:
    read-timeout: